export const PLAY = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",

  PLAY_NORMAL_REQUEST: "PLAY_NORMAL_REQUEST",
  PLAY_NORMAL_SUCCESS: "PLAY_NORMAL_SUCCESS",

  PLAY_DOUBLE_REQUEST: "PLAY_DOUBLE_REQUEST",
  PLAY_DOUBLE_SUCCESS: "PLAY_DOUBLE_SUCCESS",

  PLAY_RISK_REQUEST: "PLAY_RISK_REQUEST",
  PLAY_RISK_SUCCESS: "PLAY_RISK_SUCCESS",

  PLAY_BOMB_REQUEST: "PLAY_BOMB_REQUEST",
  PLAY_BOMB_SUCCESS: "PLAY_BOMB_SUCCESS"
};

export const DATA = {
  GET_TOP_LIST: "GET_TOP_LIST",

  GET_BOTTOM_LIST: "GET_BOTTOM_LIST",

  GET_ADMIN_LIST: "GET_ADMIN_LIST",

  GET_COUNTS: "GET_COUNTS"
};
